# Generated by Django 5.2.5 on 2025-10-09 17:02

import django.core.validators
import django.db.models.deletion
import pharmacy.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_no', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medicine_attachments/')),
                ('unit', models.CharField(choices=[('Pk', 'Pk'), ('Bottle', 'Bottle'), ('Sachet', 'Sachet'), ('Ampule', 'Ampule'), ('Vial', 'Vial'), ('Tin', 'Tin'), ('Strip', 'Strip'), ('Tube', 'Tube'), ('Box', 'Box'), ('Cosmetics', 'Cosmetics'), ('10 x 100', '10 x 100'), ('Of 10', 'Of 10'), ('Of 20', 'Of 20'), ('Of 14', 'Of 14'), ('Of 28', 'Of 28'), ('Of 30', 'Of 30'), ('Suppository', 'Suppository'), ('Pcs', 'Pcs')], default='Pcs', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.department')),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('refill_date', models.DateField(default=pharmacy.models.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.department')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='pharmacy.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounted_sales', to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.sale')),
            ],
        ),
    ]
