# Generated by Django 5.2.5 on 2025-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='FSNO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
