# Generated by Django 5.2.5 on 2025-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_fsno_medicine_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
