# Generated by Django 5.2.5 on 2025-10-01 18:22

import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_department_id_alter_medicine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='refill_date',
            field=models.DateField(default=pharmacy.models.today),
        ),
    ]
