# Generated by Django 5.2.5 on 2025-10-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='FSNO',
            field=models.CharField(blank=True, null=True),
        ),
    ]
