# Generated by Django 5.2.5 on 2025-10-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_medicine_code_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacy.department'),
        ),
    ]
